### ISSUE TITLE
[BUG] hand gesture change disabled in studio

### ISSUE THREAD

**Issue by StevenLiuVFX** [hooh-hooah/IL_Heelz#10]
**Describe the bug**
can not change hand gesture in studio after update to 1.1

it is just this simple.
choose a chara in studio, select it, go to animation, animate, choose hands, the hand gesture selection does nothing, no matter the chara has heels on or not.
after tested it a little bit, found out you can still use hand gesture selection only if you open IK. so this bug only happens in FK and normal studio environment.

after remove heelz.dll, the hand gesture selection works again. 
and all previous version does not have this bug, only 1.1 has this issue.

**Comment by hooh-hooah** [comment]
Fixed the issue. Closing.
