### ISSUE TITLE
[BUG] feet scale and rotation incorrect when using IK with bone modifier

### ISSUE THREAD

**Issue by xiaoxufeiji1a** [hooh-hooah/IL_Heelz#12]
**Describe the bug**
In Studio:
> Scale bug:
Feet scale was changed by ABMX(or other plugin that could change bone) and it works well.
Feet with heels will come back to default scale when I turn ON IK pose.
Rotation bug:
Feet rotations will always add a specific angle.
That means when I switching between FK/IK.It will goes wrong angle.

In Main Game:
> Scale bug:
Scale bug is still inside Character Creation,I guess some pose using IK and it will bug like above.

**To Reproduce (VERY IMPORTANT)**
Steps to reproduce Scale Bug:
1. Play Main Game/Studio
2. Set girl's feet scale using any bone modifier
3. Wear Heels and use IK pose
4. Feet scale will incorrectly set to default

Steps to reproduce Rotation Bug:
1. Play Studio
2. Use FK to set a pose
3. Click "Copy to IK" and Turn to IK
4. Feet will rotate wrong

**Expected behavior**
Heels will correctly multiply (feet bone scale) with (heel scale)

**Screenshots / Media (IMPORTANT)**
https://youtu.be/0DwkRcArI9E
This video shown Scale bug at first,and shown rotation bugs at second.

**Environment:**
This bug happend for long days,from old game version to new(I tested it now 1.0.7)
I have tried using ScrewThisNoise's repack.
I also have tried using only these plugins(various version): BepInEx + AI_BepisPlugins + XUnity.AutoTranslator + AIAPI + AIABMX + Heelz 1.11b
Whatever using repack or not, it seems always has this bug.

**Additional note**

**Comment by hooh-hooah** [comment]
Well I wish i can fix this but it seems it's really complicate

**Comment by xiaoxufeiji1a** [comment]
> Well I wish i can fix this but it seems it's really complicate

thanks for support and scale bug is really important one
