### ISSUE TITLE
[BUG] Trojan horse found

### ISSUE THREAD

**Issue by Gyrci** [hooh-hooah/IL_Heelz#14]
**Describe the bug**
Trojan horse found in .dll file. Had to be quarantined and removed.

**To Reproduce (VERY IMPORTANT)**
1. Try run Main Game/Studio
2. Windows Antivirus notices trojan horse 
3. Yeah this is it.

**Expected behavior**
Full game/Studio unable to open unless trojan horse is allowed

**Environment:**
Using BR 4.0

![image](https://user-images.githubusercontent.com/65111685/81499021-a9511800-92c8-11ea-83fc-620d265b0abb.png)

**Comment by hooh-hooah** [comment]
Well This is strange, I didn't included any trojan or infected by trojan
I'll release the binary

**Comment by Gyrci** [comment]
Thanks. There was no trojan horse reported after Better Repack updates
however.
